### PR TITLE
Conventional commits

### PR DESCRIPTION
**Pull request by javier-godoy**

### CODE REVIEW

**Review by ngonzalezpazFC — COMMENTED** [review]
dd9cabf pom changes could be in a different commit (build)?

9bf1751 assembly.xml changes could be in a different commit (ci?)?

**Comment by javier-godoy** [comment]
> dd9cabf pom changes could be in a different commit (build)? ⚠
Awaiting resolution of FlowingCode/DevelopmentConventions/issues/12

> 9bf1751 assembly.xml changes could be in a different commit (ci?) ✔
Done. As mentioned in https://github.com/FlowingCode/DevelopmentConventions/issues/12#issuecomment-742718469 I understand it belongs to the same commit that updates the pom. Regarding ci versus build, that needs to be addressed in the guidelines (https://github.com/FlowingCode/DevelopmentConventions/issues/10)

**Comment by javier-godoy** [comment]
> dd9cabf pom changes could be in a different commit (build)?
No (because the changes in POM are required in order to run the SerializationTest)

**Comment by javier-godoy** [comment]
@ngonzalezpazFC Please review

**Comment by ngonzalezpazFC** [comment]
> 
> 
> @ngonzalezpazFC Please review

LGTM

**Pull request merged**
